### ISSUE TITLE
NullPointerException FlutterExifRotationPlugin.java:132

### ISSUE THREAD

**Issue by diegolaballos** [NGhebreial/flutter_exif_rotation#7]
I'm getting this crash on Crashlytics:

>Caused by java.lang.NullPointerException
>Attempt to invoke virtual method 'java.lang.Object >io.flutter.plugin.common.MethodCall.argument(java.lang.String)' on a null object reference
>io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.launchRotateImage
>io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.launchRotateImage (FlutterExifRotationPlugin.java:132)
>io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.onRequestPermissionsResult (FlutterExifRotationPlugin.java:98)
>io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult (FlutterPluginRegistry.java:203)
>io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult (FlutterActivityDelegate.java:128)
>io.flutter.app.FlutterActivity.onRequestPermissionsResult (FlutterActivity.java:137)

**Comment by juliengit2** [comment]
We have the same issue, it happen when we use the api 28 (targetSdkVersion 28), no problem appear with the version 27. It's quite critical 'cause the migration to api 28 will be required soon to publish new updates (required in August for new apps), did you find how to solve that ?

**Comment by NGhebreial** [comment]
I will take a look as soon as I can. Thanks for that info, is really useful

**Comment by juliengit2** [comment]
thank you! we are waiting impatiently for a new update:) don't hesitate if you need further information...

**Comment by juliengit2** [comment]
some additional information : 
I tried to change the flutter channel and the error disappeared, here is the behavior :

flutter channel stable (what I used before) => cause crash
using channel dev => OK

**Comment by NGhebreial** [comment]
So maybe the problem is with Flutter itself? 
@diegolaballos  Can you try this also and tell me if it's working for you?

**Comment by NGhebreial** [comment]
I just published an update that solves this, please take a look

**Comment by juliengit2** [comment]
I tried your update with api 28 using channel master and no crash for present moment, thank you!

**Comment by itsmejohndoe** [comment]
Hey guys!

Getting this error when running on a new project with targetSdkVersion 29 (tried with 28 and the error persists).

Any clues?

E/MethodChannel#flutter_exif_rotation(31760): Failed to handle method call
E/MethodChannel#flutter_exif_rotation(31760): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
E/MethodChannel#flutter_exif_rotation(31760): 	at androidx.core.content.ContextCompat.checkSelfPermission(ContextCompat.java:544)
E/MethodChannel#flutter_exif_rotation(31760): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin$1.isPermissionGranted(FlutterExifRotationPlugin.java:54)
E/MethodChannel#flutter_exif_rotation(31760): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.rotateImage(FlutterExifRotationPlugin.java:117)
E/MethodChannel#flutter_exif_rotation(31760): 	at io.flutter.plugins.flutterexifrotation.FlutterExifRotationPlugin.onMethodCall(FlutterExifRotationPlugin.java:84)
E/MethodChannel#flutter_exif_rotation(31760): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter_exif_rotation(31760): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter_exif_rotation(31760): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter_exif_rotation(31760): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_exif_rotation(31760): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter_exif_rotation(31760): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutter_exif_rotation(31760): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#flutter_exif_rotation(31760): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_exif_rotation(31760): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter_exif_rotation(31760): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter (31760): PlatformException(error, Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference, null)

**Comment by itsmejohndoe** [comment]
Found it! 

The problem is: generating new apps using Flutter stable doesn't generate the onCreate method on MainActivity anymore. So i had to manually put this on my MainActivity:

`override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }`
